### ISSUE TITLE
Plans on adding this to AUR

### ISSUE THREAD

**Issue by PhilsLab** [tenox7/ttyplot#1]
Are there any plans on adding this to the Arch User Repository?

**Comment by 0xC0FFEE** [comment]
Someone took care of this[1] already.

Btw: thank you so much for your effort with ttyplot. This is a fantastic extension for everyone's toolbox.

[1] https://aur.archlinux.org/packages/ttyplot-git/

**Comment by PhilsLab** [comment]
@0xC0FFEE Thanks for letting us know!

**Comment by tenox7** [comment]
Wow thank you!
