### ISSUE TITLE
[1.5.2] `ttyplot -c X -2` fails to use ASCII character "X" for drawing?

### ISSUE THREAD

**Issue by hartwork** [tenox7/ttyplot#113]
Hi!

I ran into something by accident that to me looks like there could be more issues with the command line parsing than just #102 that was fixed by #103 recently. This is what I found:

```console
# git rev-parse HEAD
07ce2f904f0a24ab46c0af170fa65cbb3bfe62bb

# uname -s
Linux

# make

# ./ttyplot -2 -c X <<<'1 2'  # good, draws using the "X" character as expected

# ./ttyplot -c X -2 <<<'1 2'  # bad, draws using default pipe ("|") character, no error reported
```

Do you get the same? Am I using it wrong?

Thanks, Sebastian

**Comment by edgar-bonet** [comment]
I do get the same. [`ttyplot` forcibly sets `plotchar` to the ASCII pipe when the option `-2` is provided][1]. Not sure why, but this behavior is here since the initial commit.

[1]: ..//blob/master/ttyplot.c#L306

**Comment by hartwork** [comment]
@edgar-bonet okay wow! I think just dropping that line will be a good fix today. Pull request coming…
