### ISSUE TITLE
[1.6.3] Pretends to be 1.6.2. Re-release as 1.6.4 after a fix?

### ISSUE THREAD

**Issue by hartwork** [tenox7/ttyplot#178]
Hi @tenox7,

1.6.3 would have needed something like commit f187abf3001853c5739cc3c8278dca998856fe4d to make it say that's release 1.6.3. Could you bump to 1.6.4 in a pull request and then make another release after merge?

Thanks and best, Sebastian

**Comment by tenox7** [comment]
aaah thanks sorry for this
fixed!
thanks again!!!!!

**Comment by hartwork** [comment]
@tenox7 I did say "pull request" for a reason :disappointed: Your commit 9bbca81666c20d29174ff0121b03ceb7d9cd873e broke CI on master now: that's… not supposed to happen. Could you fix it through another pull request please? `master` is only for merges from pull request, please.
