### ISSUE TITLE
[1.6.4] CI is broken on `master`

### ISSUE THREAD

**Issue by hartwork** [tenox7/ttyplot#179]
@tenox7 commit 9bbca81666c20d29174ff0121b03ceb7d9cd873e broke the CI on `master`. Would be great to have fixed. Thank you! :pray:

**Comment by tenox7** [comment]
sorry let me try to fix it

**Comment by tenox7** [comment]
https://github.com/tenox7/ttyplot/pull/180

**Comment by hartwork** [comment]
Closing as fixed by cbaff3a159d83b88337b195d9f25491adda20f43…
