### ISSUE TITLE
waiting for data from stdin

### ISSUE THREAD

**Issue by trohsb** [tenox7/ttyplot#196]
I have two scripts. The first logs data read from /dev/ttyACM0 into a file:

#!/bin/bash
logFile=${1}
tail -F /dev/ttyACM0 | while read -r line
do
  echo "$(date +%s%N | cut -b1-13),${line}" >> "${logFile}"
  echo ${line}
done

The second which tails that logfile removes the timestamp and pipes the remaining value into ttyplot:

#!/bin/bash
logFile=${1}
tail -n 5 -F "${logFile}" | cut -d"," -f 2 | ttyplot -t "Rack Temp" -u "deg C" -m 40

The problem is that ttyplot doesn't update:

![ttyplot](https://github.com/user-attachments/assets/6ed56825-db00-4532-9f9b-7eb85b0832ca)

But if I run the first script and pipe the output into ttyplot it works fine:

./log_readings.sh op.log | ttyplot -t "Rack Temp" -u "deg C" -m 40

![ttyplot2](https://github.com/user-attachments/assets/50d8b7c9-5c04-49a5-9d5f-6823c223f3b0)

Sample data:

[op.log](https://github.com/user-attachments/files/17196076/op.log)

**Comment by tenox7** [comment]
At first glance it may be a stdio buffering problem. 
https://github.com/tenox7/ttyplot?tab=readme-ov-file#stdio-buffering
Please study the examples with `stdbuf` and `awk { print; fflush(); }`.
If none of this helps please let me know.

**Comment by trohsb** [comment]
Thanks. Adding 'stdbuf -o0' before the cut fixed the issue.

tail -n 5 -F "${logFile}" | stdbuf -o0 cut -d"," -f 2 | ttyplot -t "Rack Temp" -u "deg C" -m 40
