### ISSUE TITLE
Support for libncurses6

### ISSUE THREAD

**Issue by emk2203** [tenox7/ttyplot#20]
`ttyplot`  needs libncurses5 and libtinfo5 to be installed. I am running Lubuntu 19.04, which already uses libncurses6 and libtinfo6, so `ttyplot`throws errors: 

`ttyplot: error while loading shared libraries: libncurses.so.5: cannot open shared object file: No such file or directory`

After trying to fix by running
`sudo ln -s /usr/lib/x86_64-linux-gnu/libncurses.so.6 /usr/lib/x86_64-linux-gnu/libncurses.so.5`
`sudo ln -s /usr/lib/x86_64-linux-gnu/libtinfo.so.6 /usr/lib/x86_64-linux-gnu/libtinfo.so.5`, 

`ttyplot` is still not happy:

`ttyplot: /lib/x86_64-linux-gnu/libtinfo.so.5: version `NCURSES_TINFO_5.0.19991023' not found (required by ttyplot)`
`ttyplot: /lib/x86_64-linux-gnu/libncurses.so.5: version `NCURSES_5.0.19991023' not found (required by ttyplot)`

Could the binary `ttyplot` version for linux (ttyplot-amd64-linux) please support the ncurses6 libraries as well? It should be enough to just compile it on a ncurses/tinfo6 system.

It was easy to compile `ttyplot` after installation of libncurses-dev and libtinfo-dev, but since you supply all these binaries, it would be very comfortable to have out-of-the-box support as well.

**Comment by tenox7** [comment]
you mean for a binary release right? or is there any issue compiling source with ncurses6?
I think I should release statically build binaries just in case

**Comment by emk2203** [comment]
Yes, the binary release. Compiling source w/ ncurses6 was no problem at all, it was just the observation that the binary won't work for newer distributions (due to release in April).

**Comment by tenox7** [comment]
yeah, I tend to compile on older systems for compatibility, I guess I forgot to make it statically linked, I have opened a new issue to make release static

**Comment by tenox7** [comment]
now releases are statically linked with ncurses where possible
