### ISSUE TITLE
feature request: set minimum

### ISSUE THREAD

**Issue by EpicWink** [tenox7/ttyplot#42]
Option to set vertical axis minimum.

Currently, the minimum on the vertical axis is 0. If the value plotted fluctuates around a high value, a lot of the resolution of the fluctuations is lost due to most of the graph representing the baseline.

This is a proposal to have a command-line parameter to set the minimum of the vertical scale (similar to the maximum value, I suppose)

**Comment by EpicWink** [comment]
I always believe in keeping the API consistent, so yes, corresponding 'minimum' versions of `-s` (initial maximum / softmax) and `-m` (error-above maximum / hardmax)

**Comment by bratekarate** [comment]
I see that the PR for this issue was closed a while ago. Are there any plans to implement this/use the code from the closed PR?

**Comment by tenox7** [comment]
Yeah I would, unsure why the PR was closed. Perhaps OP could shed some light on this?

**Comment by EpicWink** [comment]
This issue's OP has no coverage on the associated PR :)

**Comment by tenox7** [comment]
the pr is merged!
