### ISSUE TITLE
added to homebrew

### ISSUE THREAD

**Issue by Amar1729** [tenox7/ttyplot#44]
Just wanted to let you know, I [added this as a package for Homebrew](https://github.com/Homebrew/homebrew-core/pull/44382), so mac users can do:

`brew install ttyplot`

**Comment by Kaligule** [comment]
This is cool, but not really an issue. Should we document it in the readme? Or justs close the issue? People searching for "homebrew" in the repository would still find this hint.

**Comment by Amar1729** [comment]
Looks like tenox7 documented it already, i just missed it when he did. closing.

**Comment by tenox7** [comment]
thank you all
