### ISSUE TITLE
Ping example on mac

### ISSUE THREAD

**Issue by abhatikar** [tenox7/ttyplot#48]
The ping example does not seem to work on mac terminal. Is it something related to buffered output ? also sed on mac does not have the option of -u .

Thanks in advance..

**Comment by abhatikar** [comment]
for now I am using a work around by creating a wrapper script and then piping it with ttyplot.
Btw I did try the stdbuf -o0 but it did not work for me. Any help or guidance would be appreciated.

```
#!/bin/bash

while [ 1 ];
do
	value=$(ping -c 1  8.8.8.8 | sed 's/^.*time=//g; s/ ms//g' | awk '{ print $1 }' | sed -n 2p)
	sleep 1
	echo $value
done
```

**Comment by tenox7** [comment]
I have not tried ping on mac, let me try to figure it out

**Comment by tenox7** [comment]
on a mac just change `-u` to `-l` in sed

**Comment by tenox7** [comment]
I have updated the readme. Closing ticket, please re-open if any issues.

**Comment by abhatikar** [comment]
sweet.!
