### ISSUE TITLE
License and Makefile

### ISSUE THREAD

**Issue by eddelbuettel** [tenox7/ttyplot#6]
I so love this project and already pointed half a dozen friends to it.  (I own a command-line tool for R called [littler](https://github.com/eddelbuettel/littler) which can work as a filter; I also pointed John Kerl of [mlr](https://github.com/johnkerl/miller) fame to it.)

Two things are missing, both pretty trivial:
- you should _a_ license; I am personally happy with GPL (>= 2), other like MIT/BSD style or Apache but not having anything is actually prohibiting use
- maybe add a two-line `Makefile`?  I know about `-lcurses` but then I am also [one of those guys](http://dilbert.com/strip/1995-06-24)

**Comment by tenox7** [comment]
Done! Thanks. I love littler and mlr.
