### ISSUE TITLE
Trigger redraw on SIGWINCH (Window resize signal)

### ISSUE THREAD

**Issue by eMPee584** [tenox7/ttyplot#61]
Otherwise, the plot will look broken until the regular refresh timeout has occurred..

**Comment by tenox7** [comment]
sounds simple enough, would you consider sending a PR?

**Comment by tenox7** [comment]
but wait, this is already there:

https://github.com/tenox7/ttyplot/blob/master/ttyplot.c#L217

is it not working correctly?

**Comment by eMPee584** [comment]
Well checked again, it doesn't seem so.. using debian's version `1.4+77.g1a1693b-2` ..

**Comment by zbits** [comment]
My slow moving graphs that update once an hour do not update on window resize:

```
netstat -b -w 3600 -I em0 | awk 'NR>3 { print $1/1048576; print $2/1048576; fflush }' | ttyplot -2 -t "IN/OUT Bandwidth in MB/s (${1}s resolution)" -u "MB/s" -c "#"
```

Using version 1.4 on OpenBSD.

**Comment by tenox7** [comment]
thanks, let me investigate a bit more

**Comment by tenox7** [comment]
> ```
> netstat -b -w 3600 -I em0 | awk 'NR>3 { print $1/1048576; print $2/1048576; fflush }' | ttyplot -2 -t "IN/OUT Bandwidth in MB/s (${1}s resolution)" -u "MB/s" -c "#"
> ```

thats actually a cool way of getting bandwidth usage! we should add it to the examples :)

**Comment by tenox7** [comment]
OK I done some testing and I think I understand the issue. So redraw() is called on SIGWINCH, however it doesn't actually repaint the screen. The screen is eventually correctly redrawn when there is data for a new refresh. In this case the screen should correctly redraw after 1 hour.

The fix would be to repaint the screen with current data in a separate function. That function would be called either from the main while loop or refresh() on SIGWINCH.

**Comment by tenox7** [comment]
ok I think I fixed it, in head master

can you download the source, compile and test?

**Comment by zbits** [comment]
That fixed it!  Thank you. 

Note that compiling it on openbsd the library "tinfo" was missing. I wasn't sure how to obtain it and the ttyplot git commits didn't explain its necessity, so I edited it out of the Makefile and ttyplot compiled and worked fine.

> thats actually a really cool way of getting bandwidth usage! @zbits would you like to send a PR for readme/examples :)

I'm new to git and have never created a PR but I will read up on it and send you one.

Thanks for the ttyplot project.  I love its simplicity.  In my case, replaced a prometheus/grafana solution.
