### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [tenox7/ttyplot#62]
The function “[endwin](https://pubs.opengroup.org/onlinepubs/007908799/xcurses/endwin.html "Suspend Curses session.")” does not belong to the list of [async-signal-safe functions](https://www.securecoding.cert.org/confluence/display/c/SIG30-C.+Call+only+asynchronous-safe+functions+within+signal+handlers "Call only asynchronous-safe functions within signal handlers.").
I guess that a different program design will be needed for [your functions “finish” and “resize”](https://github.com/tenox7/ttyplot/blob/e7c1b731813fcf1e9b403b6132e1a045b9f03fb9/ttyplot.c#L119 "Update candidates").

**Comment by tenox7** [comment]
ack, more info with links
https://stackoverflow.com/questions/52893429/after-intercepting-sigwinch-in-a-ncurses-based-program-key-presses-are-not-reco

**Comment by tenox7** [comment]
ha, thats a tricky one, reason being that I do a blocking read on stdin and redraw when there is input; so KEY_RESIZE or flag + periodic redraw cannot be used without resorting to threads. I'm thinking that perhaps `sigprocmask()` could be used to block interrupting `endwin()` with another one. Because ttyplot doesn't use endwin is not used elsewhere and no other ncurses input functions are used it may be good enough.

I really don't want to go in to threads because I like to use ttyplot on older systems that may not have these.

**Comment by elfring** [comment]
:crystal_ball: Will it matter for you if [signal notifications would be handled only by a separate thread](https://stackoverflow.com/questions/6223191/dealing-with-asynchronous-signals-in-multi-threaded-program "Dealing with asynchronous signals in multi-threaded program")?

**Comment by tenox7** [comment]
I really don't want to do threads in ttyplot. I mentioned it above. I sometimes use it on very old systems that do not have pthreads even. Also I don't like the complexity. 

I will consider/accept anything else. I like `sigwaitinfo()` and `sigprocmask()`. Also the self pipe trick looks really cool. I was actually thinking about feeding ttyplot a sync clock via pipe mixed with data like over a sync serial line. This could be interlaced with refresh events. The chart would advance only if there is data coming in.

Are you willing to send a PR? Or do you want me to look at implementing these?

**Comment by elfring** [comment]
>Also the self pipe trick looks really cool.

:crystal_ball: How far would you get with another event-driven application architecture?


>Or do you want me to look at implementing these?

:thought_balloon: Probably, yes.

Further collateral evolution would be nice, wouldn't it?

**Comment by tenox7** [comment]
Hahaha. 

BTW I started looking at writing a more modern replacement for ttyplot. Most likely in Go, using something like termbox-go or maybe simpler termui. It will have colors, braille character charts, bar charts, etc. Ttyplot2 will be the new, modern, fancy, flashy thing. I want ttyplot1 to remain pure, plain and simple. Compatible with older Unix like AIX, HPUX, IRIX, Solaris, Unixware, SCO, Tru64, dont use threads, unicode, etc.

**Comment by tenox7** [comment]
I added sigprocmask() for now. Feel free to submit a PR with something better.

**Comment by elfring** [comment]
:thought_balloon: I find your signal handler implementations still async-signal-unsafe.

**Comment by tenox7** [comment]
Yes thats true. I'm not closing the ticket. However fixing this will require much bigger changes. This is just a quick patch for a most obvious issue.

**Comment by tenox7** [comment]
ok, I did some more reading and experimentation; turns out that ncurses installs it's own signal handlers if app doesn't do it on it's own; I can simply remove `resize()` and `finish()`, signal handlers and everything will magically still work correctly

would this be async signal safe? 🤷
