### ISSUE TITLE
Program immediately quits

### ISSUE THREAD

**Issue by themightyoarfish** [tenox7/ttyplot#63]
On macOS 12.5.1, plotting from stdin does not work:

```
 echo "1 2 3 4 5" | ttyplot
```

immediately exits. With longer input, one can see the plot flashing by, before the program quits and nothing is left.

**Comment by tenox7** [comment]
yeah, this is by design, please refer to the FAQ for work-around:

https://github.com/tenox7/ttyplot#frequently-questioned-answers

Saying that, ttyplot could potentially just sit forever saying "end of stream" or something like that, so the plot is not lost.

**Comment by tenox7** [comment]
ok so I have changed the default behavior; from now on ttyplot will just sit and wait with a message instead of quitting

https://github.com/tenox7/ttyplot/commit/9be5beac8d723cd4a834bf810d6aab65d22150f5
