### ISSUE TITLE
Plans for a post-1.4 release off Git master?

### ISSUE THREAD

**Issue by hartwork** [tenox7/ttyplot#64]
Hi @tenox7,

thanks for sharing ttyplot as Software Libre! :+1: I noticed that there are [90+ commits on `master` since release 1.4](https://github.com/tenox7/ttyplot/compare/1.4...master) and that Debian-based distros have packaged post-1.4 Git snapshots:

![XXXX](https://camo.githubusercontent.com/6b858205f899312558544ef80cfd18204aa11b29ee310ce1efa1e5b1164b31e1/68747470733a2f2f7265706f6c6f67792e6f72672f62616467652f766572746963616c2d616c6c7265706f732f747479706c6f742e737667)

To my understanding both indicate, that there is lack for a more recent release.
Are there any plans to cut a release 1.5+ off `master`? I'm considering packaging ttyplot for Gentoo, and that would be a great match.

Thanks and best, Sebastian

**Comment by tenox7** [comment]
Plans are there, but things are slow at the moment with layoffs and economy down. I want to add couple of features before I release 1.5. I think it still may be a few weeks or months even before I have time for this. Lets keep this open.

**Comment by tenox7** [comment]
recently fixed an issue with sigwinch / refresh so that may be a good candidate for a release, so ...  soon

**Comment by hartwork** [comment]
@tenox7 yes please :+1: 

For anyone else reading: related commit for sigwinch is f40a11bfaf8b36767fe51099b676b3f2fa70edd5

**Comment by tenox7** [comment]
Also added sigprocmask to block sigwinch interrupting sigwinch handler. I'm going to start testing on different platforms and make a release if no further issues with this.

**Comment by hartwork** [comment]
@tenox7 since you mention testing, I notice that there is no CI yet. I can add a simple GitHub Actions CI for Linux shortly as a pull request if that's welcome. It should protect against future build error regressions and also has a chance to uncover compilation issues with modern compilers. What do you think?

**Comment by tenox7** [comment]
it's coming soon, someone wants to add `-v` option to print version number and then we can make 1.5

**Comment by tenox7** [comment]
done

**Comment by hartwork** [comment]
> done

@tenox7 thanks!
