### ISSUE TITLE
handle window resize on older systems

### ISSUE THREAD

**Issue by tenox7** [tenox7/ttyplot#81]
older curses versions do not support window resize on `SIGWINCH`, allegedly `TIOCGWINSZ` can be used to obtain correct terminal size

**Comment by hartwork** [comment]
Is this about configure argument `--enable-sigwinch` of ncurses?

```console
# [..]/ncurses-6.4/configure --help | grep sigwinch
  --enable-sigwinch       compile with SIGWINCH handler
```

**Comment by tenox7** [comment]
thats if you have ncurses..., lets just say we won't support older systems going forward
