### ISSUE TITLE
Average should be calculated from the available samples instead of the total number of potentially availalbe values

### ISSUE THREAD

**Issue by MIvanchev** [tenox7/ttyplot#85]
When I run my plots the initially average is very low and gradually increases to the expected value. I think it's better if the average is correct right off the start by dividing the sum by the number of samples really available vs by the total number of displayable samples. It would be also useful if one can specify the interval / number of samples over which the statistics are generated because for small terminal sizes they'd be jumpy.

**Comment by tenox7** [comment]
ha interesting, you're totally right, I'll try to add it in

**Comment by tenox7** [comment]
also PRs are welcome 🤣

**Comment by MIvanchev** [comment]
I'll try! :)

**Comment by MIvanchev** [comment]
So it appears the first part of this issue was resolved through https://github.com/tenox7/ttyplot/commit/a3ed604f0ea5e115b36cde0ba97eae23f73122d1 3 years ago :)
