### ISSUE TITLE
Release a new version and support -v option?

### ISSUE THREAD

**Issue by MIvanchev** [tenox7/ttyplot#88]
I just noticed 1.4 is from 2019 and a lot of features have been implemented since then. Maybe release 1.5 soon? :) Would be also cool if there was a -v option to print out the version and exit immediately. I could provide a MR for this.

**Comment by tenox7** [comment]
Yeah I should do it...

**Comment by tenox7** [comment]
ok please send a pr/mr for `-v` and then I'll release

**Comment by MIvanchev** [comment]
MR also adds -h parameter and changes exit code to 1 for the error case (unrecognized option). This is consistent with other *nix tools. -h has priority over -v. An initial loop checks for -h, -v or unrecognized option to avoid setting up stuff if there's no need.
